Connie
conniejmiller/SSW555tm092017Fall pull request #14
Opened 2017-10-05 01:29 UTC by conniejmiller

refactoring after week 6 homework.

2017-10-05 05:04 UTC, vporta requested changes
Hey Connie, your test cases are failing. We shouldn't merge it. I would run the tests locally first, make sure they pass, then open up another pull request. 

I did run them locally....and again just now.  They work fine for me.  Can you tell me what you think is failing?

2017-10-06 01:26 UTC, ryancoppa commented
This is the output I see
```
$ python test.py
test_calculate_years (__main__.TestProject)
Testing the calculate_years function ... ok
test_date_compare (__main__.TestProject)
Testing the date_compare function ... ok
test_empty (__main__.TestProject)
Testing the process_words function ... ok
test_get_age (__main__.TestProject)
Testing the get_age function ... ok
test_get_name_id (__main__.TestProject)
Testing the get_name_id function ... ok
test_get_name_id_list (__main__.TestProject)
Testing the get_name_id function ... ok
test_is_deceased (__main__.TestProject)
Testing the is_deceased function ... ok
test_life_duration (__main__.TestProject)
Testing if life duration is less than 150 years ... ok
test_valid_lifetime (__main__.TestProject)
Testing the valid_lifetime function ... ok
test_valid_month (__main__.TestProject)
Testing is month is valid ... ok
test_validate_birth_dates (__main__.TestProject)
Testing the validate_indi_dates function ... Error US42: Invalid birth month for Mary /Smith/ (@I2@)
ERROR
test_validate_genders (__main__.TestProject)
validate_genders(families, individuals): ... Anomaly US21: Wife Mary /Smith/ (@I2@)in family @F1@ is not female.
ok

======================================================================
ERROR: test_validate_birth_dates (__main__.TestProject)
Testing the validate_indi_dates function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 71, in test_validate_birth_dates
    self.assertEqual(project.validate_birth_dates(individuals[5]), 'US01')
IndexError: list index out of range

----------------------------------------------------------------------
Ran 12 tests in 0.016s

FAILED (errors=1)
```

Maybe clone the code again in a new folder and try it, maybe you have some untracked files?

2017-10-06 01:26 UTC, ryancoppa requested changes
Made a comment with the output I see from running `python test.py` from a command prompt

Thanks!  I forgot I'd added data....I've now added that here.  The code is fine...just missing the new individual on the test file.

2017-10-06 02:20 UTC, ryancoppa approved these changes

2017-10-06 22:51 UTC, closed without merging